working_dir : 
filter :
  branch : master
  restrict :
    commit_count : -1  # commit_count limit or -1 to ignore limit
    # precise date or -1 to ignore date bound
    from_date : 2014-01-01
    to_date : 2019-01-01
  key_words :
    first :
      - bug
      - fix
      - check
      - issue
      - mistake
      - incorrect
      - fault
      - defect
      - error
      - flaw
      - invalid
      - fatal
      - wrong
      - damage
    second :
      - memory leak
      - error path
      - unchecked return
      - error handle
      - miss check
      - incorrect check
      - error propagation
      - return value
      - exception handle
      - check return
      - error check
  LOC : 
  NOF : 3
  file_name :
    - test
    - news
    - contribute
  ignore_case : True
output :
  dir : 
  file_name : report.db
  # diff_xxx fields denote whether outputting diff patches in corresponding folders
  diff_mid : True # whether outputting middle result
  diff_result : True  # whether outputting final result
